version: "3"
services:
  react-code-server:
    container_name: react-code-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./workspace:/home/root/workspace
      - ./code-server-data:/root/.local/share/code-server

volumes:
  workspace:
  code-server-data:
